// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: jobmaker.proto

package jobmaker

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type CreateLauncherJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace        string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RepoURL          string `protobuf:"bytes,2,opt,name=repo_u_r_l,json=repoURL,proto3" json:"repo_u_r_l,omitempty"`
	ChartReleaseName string `protobuf:"bytes,3,opt,name=chart_release_name,json=chartReleaseName,proto3" json:"chart_release_name,omitempty"`
	ChartName        string `protobuf:"bytes,4,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartVersion     string `protobuf:"bytes,5,opt,name=chart_version,json=chartVersion,proto3" json:"chart_version,omitempty"`
}

func (x *CreateLauncherJobRequest) Reset() {
	*x = CreateLauncherJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobmaker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLauncherJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLauncherJobRequest) ProtoMessage() {}

func (x *CreateLauncherJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobmaker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLauncherJobRequest.ProtoReflect.Descriptor instead.
func (*CreateLauncherJobRequest) Descriptor() ([]byte, []int) {
	return file_jobmaker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLauncherJobRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateLauncherJobRequest) GetRepoURL() string {
	if x != nil {
		return x.RepoURL
	}
	return ""
}

func (x *CreateLauncherJobRequest) GetChartReleaseName() string {
	if x != nil {
		return x.ChartReleaseName
	}
	return ""
}

func (x *CreateLauncherJobRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *CreateLauncherJobRequest) GetChartVersion() string {
	if x != nil {
		return x.ChartVersion
	}
	return ""
}

// The response message containing the greetings
type JobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobmaker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobmaker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_jobmaker_proto_rawDescGZIP(), []int{1}
}

func (x *JobResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_jobmaker_proto protoreflect.FileDescriptor

var file_jobmaker_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6a, 0x6f, 0x62, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6a, 0x6f, 0x62, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x22, 0xc7, 0x01, 0x0a, 0x18, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x72, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x75, 0x5f,
	0x72, 0x5f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x55,
	0x52, 0x4c, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x5c, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x50, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x72, 0x4a,
	0x6f, 0x62, 0x12, 0x22, 0x2e, 0x6a, 0x6f, 0x62, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6a, 0x6f, 0x62, 0x6d, 0x61, 0x6b, 0x65,
	0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x77,
	0x6a, 0x35, 0x2f, 0x6a, 0x6f, 0x62, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x6a, 0x6f, 0x62, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jobmaker_proto_rawDescOnce sync.Once
	file_jobmaker_proto_rawDescData = file_jobmaker_proto_rawDesc
)

func file_jobmaker_proto_rawDescGZIP() []byte {
	file_jobmaker_proto_rawDescOnce.Do(func() {
		file_jobmaker_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobmaker_proto_rawDescData)
	})
	return file_jobmaker_proto_rawDescData
}

var file_jobmaker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jobmaker_proto_goTypes = []interface{}{
	(*CreateLauncherJobRequest)(nil), // 0: jobmaker.CreateLauncherJobRequest
	(*JobResponse)(nil),              // 1: jobmaker.JobResponse
}
var file_jobmaker_proto_depIdxs = []int32{
	0, // 0: jobmaker.jobmaker.CreateLauncherJob:input_type -> jobmaker.CreateLauncherJobRequest
	1, // 1: jobmaker.jobmaker.CreateLauncherJob:output_type -> jobmaker.JobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobmaker_proto_init() }
func file_jobmaker_proto_init() {
	if File_jobmaker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jobmaker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLauncherJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobmaker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobmaker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobmaker_proto_goTypes,
		DependencyIndexes: file_jobmaker_proto_depIdxs,
		MessageInfos:      file_jobmaker_proto_msgTypes,
	}.Build()
	File_jobmaker_proto = out.File
	file_jobmaker_proto_rawDesc = nil
	file_jobmaker_proto_goTypes = nil
	file_jobmaker_proto_depIdxs = nil
}
